In [10]:
from CASOS import C1B1C as B1C1 #type: ignore
from CASOS import C1A as A1 #type: ignore
from CASOS import C2B2C as B2C2 #type: ignore
from CASOS import C2A as A2 #type: ignore
from CASOS import C3A3B3C as A3B3C3 #type: ignore

In [11]:
import numpy as np
import pandas as pd



In [12]:
Np = 1
Nr = 2
caso = '1B'
R = [1,2,3,4]
print(  B2C2.array_2B2C(Np,Nr,'2B',R))


ValueError: could not broadcast input array from shape (1000000,) into shape (1000,)

In [5]:
def get_data():
    FA1,PA1 = A1.array_1A(Np,Nr,R)
    dic_A1 = { }
    for i,Re in enumerate(R):
        dic_A1[f'P{i}'] = PA1[i,:]
        dic_A1[f'F{i}'] = FA1[i,:]
    data_A1 = pd.DataFrame(dic_A1)

    FB1,PB1 = B1C1.array_1B1C(Np,Nr,'1B',R)
    dic_B1 = { }
    for i,Re in enumerate(R):
        dic_B1[f'P{i}'] = PB1[i,:]
        dic_B1[f'F{i}'] = FB1[i,:]
    data_B1 = pd.DataFrame(dic_B1)

    FC1,PC1 = B1C1.array_1B1C(Np,Nr,'1C',R)
    dic_C1 = { }
    for i,Re in enumerate(R):
        dic_C1[f'P{i}'] = PC1[i,:]
        dic_C1[f'F{i}'] = FC1[i,:]
    data_C1 = pd.DataFrame(dic_C1)

    return data_A1,data_B1,data_C1 



[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
